sudo: false

language: ruby
rvm:
  - 2.1

os:
  - linux
  
# Whitelists gh-pages fortesting on Travis CI
branches:
  only:
    - gh-pages
  
env:
  global:
    # speeds up installing html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external
  - ./.compile.sh
